spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/employe
    password: mouna123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  servlet:
    context-path: /employee-service
  port: 8082

